# Generated by Django 5.2.17 on 2026-09-24 22:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trucks', '0003_remove_truck_unique_active_license_plate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['display_name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ImportRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=32)),
                ('installation', models.CharField(max_length=64)),
                ('entity', models.CharField(max_length=32)),
                ('legacy_id', models.CharField(max_length=64)),
                ('target_id', models.PositiveBigIntegerField()),
                ('fingerprint', models.CharField(max_length=64)),
                ('payload', models.JSONField()),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source', 'installation', 'entity', 'legacy_id'), name='fleet_source_identity')],
            },
        ),
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_snapshot', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('quoted_value', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('deadline', models.DateField()),
                ('status', models.CharField(choices=[('pendente', 'pendente'), ('em_andamento', 'em_andamento'), ('concluido', 'concluido'), ('cancelado', 'cancelado')], default='pendente', max_length=20)),
                ('version', models.PositiveIntegerField(default=0)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='operations.customer')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='trucks.truck')),
            ],
            options={
                'ordering': ['deadline', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OrderTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(max_length=20)),
                ('next_status', models.CharField(max_length=20)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transitions', to='operations.serviceorder')),
            ],
            options={
                'ordering': ['occurred_at', 'id'],
            },
        ),
    ]
