server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    client_max_body_size 2m;
    add_header X-Content-Type-Options nosniff always;
    location /api/ {
        proxy_pass http://api:8000;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
    location /assets/ { try_files $uri =404; }
    location / { try_files $uri $uri/ /index.html; }
}
