import {test,expect} from "@playwright/test";
test("retirement acceptance: migrated data, secure session, viewer denial and admin lifecycle",async({page})=>{
  await expect.poll(async()=>{try{return (await page.request.get("/api/session/")).status();}catch{return 0;}},{timeout:60000}).toBe(200);
  await page.goto("/");
  await page.getByLabel("Username",{exact:true}).fill("rehearsal-viewer");
  await page.getByLabel("Password",{exact:true}).fill(process.env.FLEET_REHEARSAL_PASSWORD!);
  await page.getByRole("button",{name:"Sign in",exact:true}).click();
  await expect(page.getByRole("button",{name:"Sign out",exact:true})).toBeVisible();
  const checks=await page.evaluate(async()=>{
    const session=await (await fetch("/api/session/")).json();
    const orders=await (await fetch("/api/orders/")).json();
    const customers=await (await fetch("/api/customers/")).json();
    const vehicles=await (await fetch("/api/trucks/")).json();
    const denied=await fetch("/api/customers/",{method:"POST",headers:{"Content-Type":"application/json","X-CSRFToken":session.csrfToken},body:JSON.stringify({display_name:"Must not create"})});
    return {orders:orders.count,customers:customers.count,vehicles:vehicles.count,denied:denied.status};
  });
  expect(checks.denied).toBe(403);
  expect(checks.orders).toBeGreaterThan(0);
  expect(checks.customers).toBeGreaterThan(0);
  expect(checks.vehicles).toBeGreaterThan(0);
  await page.getByRole("button",{name:"Service orders",exact:true}).click();
  await expect(page.getByRole("table")).toBeVisible();
  await page.getByRole("button",{name:"Sign out",exact:true}).click();
  await page.getByLabel("Username",{exact:true}).fill("rehearsal");
  await page.getByLabel("Password",{exact:true}).fill(process.env.FLEET_REHEARSAL_PASSWORD!);
  await page.getByRole("button",{name:"Sign in",exact:true}).click();
  await expect(page.getByRole("button",{name:"Sign out",exact:true})).toBeVisible();
  const result=await page.evaluate(async()=>{
    const csrf=(await (await fetch("/api/session/")).json()).csrfToken;
    const headers={"Content-Type":"application/json","X-CSRFToken":csrf};
    const created=await fetch("/api/orders/",{method:"POST",headers,body:JSON.stringify({customer_snapshot:"Acceptance only",description:"Disposable lifecycle check",quoted_value:"12.34",deadline:"2020-01-01"})});
    const order=await created.json();
    const transition=await fetch("/api/orders/"+order.id+"/",{method:"PATCH",headers,body:JSON.stringify({status:"em_andamento",version:0})});
    const updated=await transition.json();
    const vehicles=await (await fetch("/api/trucks/")).json();
    const first=vehicles.results[0];
    const duplicate=await fetch("/api/trucks/",{method:"POST",headers,body:JSON.stringify({license_plate:first.license_plate,brand:"Collision",model:"Collision",manufacturing_year:2020})});
    return {created:created.status,transition:transition.status,quote:updated.quoted_value,history:updated.transitions.length,duplicate:duplicate.status};
  });
  expect(result).toEqual({created:201,transition:200,quote:"12.34",history:1,duplicate:400});
});
