# Generated by Django 4.2.7 on 2026-01-18 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='license_plate',
            field=models.CharField(db_index=True, max_length=7),
        ),
        migrations.AddIndex(
            model_name='truck',
            index=models.Index(fields=['deleted_at'], name='trucks_truc_deleted_e6735c_idx'),
        ),
        migrations.AddConstraint(
            model_name='truck',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('license_plate',), name='unique_active_license_plate'),
        ),
    ]
