# Generated by Django 5.2.17 on 2026-09-24 22:57

from django.db import migrations, models
import re


def validate_source(apps, schema_editor):
    Truck = apps.get_model("trucks", "Truck")
    seen = set()
    for truck in Truck.objects.using(schema_editor.connection.alias).filter(deleted_at__isnull=True).iterator():
        plate = truck.license_plate.upper().replace("-", "").replace(" ", "")
        if not re.fullmatch(r"[A-Z]{3}[0-9][A-Z0-9][0-9]{2}", plate) or plate in seen:
            raise RuntimeError("Reconcile invalid or duplicate active plates before migration; truck ID " + str(truck.pk))
        seen.add(plate)


def populate_active_plate(apps, schema_editor):
    Truck = apps.get_model("trucks", "Truck")
    for truck in Truck.objects.using(schema_editor.connection.alias).filter(deleted_at__isnull=True).iterator():
        plate = truck.license_plate.upper().replace("-", "").replace(" ", "")
        Truck.objects.using(schema_editor.connection.alias).filter(pk=truck.pk).update(license_plate=plate, active_plate=plate)


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0002_truck_deleted_at_alter_truck_license_plate_and_more'),
    ]

    operations = [
        migrations.RunPython(validate_source, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name='truck',
            name='unique_active_license_plate',
        ),
        migrations.AddField(
            model_name='truck',
            name='active_plate',
            field=models.CharField(blank=True, editable=False, max_length=7, null=True, unique=True),
        ),
        migrations.RunPython(populate_active_plate, migrations.RunPython.noop),
        migrations.AddField(
            model_name='truck',
            name='fipe_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='truck',
            name='fipe_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
