# Generated by Django 5.2.17 on 2026-09-25 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0003_remove_truck_unique_active_license_plate_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='truck',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('active_plate__isnull', True), ('deleted_at__isnull', False)), models.Q(('active_plate', models.F('license_plate')), ('active_plate__isnull', False), ('deleted_at__isnull', True)), _connector='OR'), name='active_plate_matches_vehicle'),
        ),
    ]
